# Generated by Django 4.2 on 2023-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
